import type eslint from 'eslint';
import parentConfig from '@w5s/eslint-config/dist/ignore.js';
import { ESLintConfig } from '@w5s/dev';

const config: eslint.Linter.Config = ESLintConfig.concat({
  ...parentConfig,
  ignorePatterns: [
    ...(parentConfig.ignorePatterns ?? []),
    // Autogenerated swagger files
    '**/swagger.yaml',
  ],
});

export = config;
